Repository DebugSwift/DebugSwift, pull requests merged in 2024-04, with the labels that each got.

#54 feat: resolve duplication of data
  DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
Labels: bugfix 🐞

#57 [Bugfix] Add response data
  DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
Labels: bugfix 🐞

#60 [Improvements] Add cell swipe action on requests list
  DebugSwift/Resources/Base.lproj/Localizable.strings
  DebugSwift/Resources/en.lproj/Localizable.strings
  DebugSwift/Resources/pt-BR.lproj/Localizable.strings
  DebugSwift/Sources/Features/Network/Main/Network.Controller.swift
  Example/Podfile.lock
  Example/Pods/Local Podspecs/DebugSwift.podspec.json
  Example/Pods/Manifest.lock
  Example/Pods/Target Support Files/DebugSwift/DebugSwift-Info.plist
  Example/Pods/Target Support Files/DebugSwift/ResourceBundle-DebugSwift-DebugSwift-Info.plist
Labels: enhancement ✨

#63 [Bugfix] Ci
  .github/workflows/git-version.yml
Labels: bugfix 🐞

#64 [Release] Novo
  .github/workflows/git-version.yml
  DebugSwift.podspec
  DebugSwift/Resources/Base.lproj/Localizable.strings
  DebugSwift/Resources/en.lproj/Localizable.strings
  DebugSwift/Resources/pt-BR.lproj/Localizable.strings
  DebugSwift/Sources/Features/Interface/Helpers/UserInterfaceToolkit.swift
  DebugSwift/Sources/Features/Interface/Interface.Controller.swift
  DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
  DebugSwift/Sources/Features/Network/Main/Network.Controller.swift
  Example/Pods/Pods.xcodeproj/project.pbxproj
Labels: feature 💡

#65 [Bugfix] Fix iPad version and Improve crash trace
  DebugSwift/Sources/Features/App/Crash/Detail/CrashDetailViewController.swift
  DebugSwift/Sources/Features/App/Crash/Detail/CrashDetailViewModel.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/CallStackSymbols/CallStackParser.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/CallStackSymbols/CwlDemangle.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/CallStackSymbols/Thread+.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/CrashHandler.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/CrashModel.swift
  DebugSwift/Sources/Features/App/Crash/Helpers/Trace.swift
  DebugSwift/Sources/Features/App/Crash/Main/CrashViewController.swift
  DebugSwift/Sources/Features/App/Crash/Main/CrashViewModel.swift
  DebugSwift/Sources/Helpers/Extensions/Collection+.swift
  DebugSwift/Sources/Helpers/Extensions/Date+.swift
  DebugSwift/Sources/Helpers/Extensions/Dictionary+.swift
  DebugSwift/Sources/Helpers/Extensions/String+.swift
  DebugSwift/Sources/Helpers/Extensions/UITableViewCell+.swift
  DebugSwift/Sources/Helpers/Managers/WindowManager.swift
  DebugSwift/Sources/Helpers/Tools/Debug.swift
  Example/Example.xcodeproj/project.pbxproj
  Example/Example/ViewController.swift
  Example/Pods/Pods.xcodeproj/project.pbxproj
Labels: bugfix 🐞

#66 [Bugfix] Fix hang
  DebugSwift/Sources/Features/Performance/Helpers/Performance.Toolkit.swift
Labels: bugfix 🐞
