Repository DebugSwift/DebugSwift, pull requests merged in 2024-11, with the labels that each got.

#99 Add automatic appearance option
  DebugSwift/Sources/Helpers/Extensions/UIColor+.swift
  DebugSwift/Sources/Helpers/Managers/Theme.swift
  DebugSwift/Sources/Settings/DebugSwift.swift
  Example/Example/AppDelegate.swift
Labels: enhancement ✨

#100 Fix crash when removing simulated location
  DebugSwift/Sources/Features/App/Location/Helpers/CLLocationManager.swift
Labels: bugfix 🐞

#104 [Release] 0.3.7
  .github/workflows/git-version.yml
  DebugSwift/Sources/Features/App/App.Controller.swift
  DebugSwift/Sources/Features/App/Location/Helpers/CLLocationManager.swift
  DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
  DebugSwift/Sources/Features/Network/Helpers/Helpers/HTTPProtocolDelegate.swift
  DebugSwift/Sources/Helpers/Extensions/Data+.swift
  DebugSwift/Sources/Helpers/Extensions/UIColor+.swift
  DebugSwift/Sources/Helpers/Managers/Theme.swift
  DebugSwift/Sources/Settings/DebugSwift.Network.swift
  DebugSwift/Sources/Settings/DebugSwift.swift
  Example/Example/AppDelegate.swift
  Example/Example/Base.lproj/Main.storyboard
  Example/Example/Helpers/LeakViewController.swift
  Example/Example/pt-BR.lproj/Main.strings
  Example/Pods/Target Support Files/DebugSwift/DebugSwift-Info.plist
  Example/Pods/Target Support Files/DebugSwift/ResourceBundle-DebugSwift-DebugSwift-Info.plist
Labels: feature 💡

#105 [Release] Fix 0.3.7
  .github/workflows/git-version.yml
Labels: feature 💡

#106 [Release] Correção 0.3.7
  .github/workflows/git-version.yml
  DebugSwift/Sources/Features/App/App.Controller.swift
Labels: feature 💡
