Repository DebugSwift/DebugSwift, pull requests merged in 2025-07, with the labels that each got.

#189 [Bugfix-Add-Custom-Protocol] Bugfix-Add-Custom-Protocol
  DebugSwift/Sources/Features/Interface/ViewDebugger/SnapshotView.swift
  DebugSwift/Sources/Features/Interface/ViewDebugger/SnapshotViewConfiguration.swift
  DebugSwift/Sources/Features/Interface/ViewDebugger/ViewElement.swift
  DebugSwift/Sources/Features/Network/Helpers/HTTPProtocol.swift
  DebugSwift/Sources/Features/Network/Helpers/Helpers/SwizzleSessionConfiguration.swift
  DebugSwift/Sources/Features/Performance/Helpers/Performance.LeakDetector.swift
  DebugSwift/Sources/Helpers/FloatingButton/Views/FloatBallView/FloatBallView.swift
  Example/Example/ExampleApp.swift
Labels: bugfix 🐞

#193 [Bugfix] Stdout Capture
  DebugSwift/Sources/Features/App/Console/Helpers/StderrCapture.swift
  DebugSwift/Sources/Features/App/Console/Helpers/StdoutCapture.swift
  DebugSwift/Sources/Helpers/Tools/Debug.swift
  Example/Example/ContentView.swift
  Example/Example/CrashesTests/DeadlockTestView.swift
  Example/Example/ExampleApp.swift
  Example/Example/Hyperion/HyperionSwiftDemoView.swift
Labels: Bugfix

#194 [Feature] Improve Readme
  README.md
  VERSIONING.md
Labels: Feature

#196 [Feature] Improve Performance Memory
  DebugSwift/Resources/Base.lproj/Localizable.strings
  DebugSwift/Resources/en.lproj/Localizable.strings
  DebugSwift/Resources/pt-BR.lproj/Localizable.strings
  DebugSwift/Sources/Features/Performance/Helpers/Performance.MemoryWarning.swift
  DebugSwift/Sources/Features/Performance/Performance.Controller.swift
Labels: Feature

#197 [Feature] Improve Performance Memory
  DebugSwift/Sources/Features/Resources/GenericList/Resources.Generic.Controller.swift
Labels: Feature

#199 Fix: Disable interactive pop gesture in WindowManager
  DebugSwift/Sources/Helpers/Managers/WindowManager.swift
Labels: Bugfix

#201 [Bugfix] Render Tracker
  DebugSwift/Sources/Base/FeatureBase.swift
  DebugSwift/Sources/Features/App/Console/ConsoleViewModel.swift
  DebugSwift/Sources/Features/App/Console/Helpers/ConsoleOutput.swift
  DebugSwift/Sources/Features/App/Console/Helpers/StderrCapture.swift
  DebugSwift/Sources/Features/App/Console/Helpers/StdoutCapture.swift
  DebugSwift/Sources/Features/Interface/Interface.Controller.swift
  DebugSwift/Sources/Features/Interface/SwiftUI/SwiftUIRenderTracker.swift
  DebugSwift/Sources/Helpers/Extensions/UIView+.swift
  DebugSwift/Sources/Settings/DebugSwift.swift
  DebugSwift/Sources/Settings/FeatureHandling.swift
  Example/Example/ExampleApp.swift
  Example/ExampleTests/Tests/Base/FeatureBaseTests.swift
  Example/ExampleTests/Tests/Features/Interface/SwiftUIRenderTrackingTests.swift
  Example/ExampleTests/Tests/Helpers/Extensions/UIView+Tests.swift
  Example/ExampleTests/Tests/Settings/DebugSwiftSwiftUIRenderTests.swift
  Example/ExampleTests/Tests/Settings/FeatureHandlingBetaTests.swift
  README.md
Labels: Bugfix
